### PR TITLE
Fix windows quoting

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
* Fix Makefile quoting for WIn32 build
* Add epicsShareFunc  for lcaMexGblInit

### CODE REVIEW

**Comment by FreddieAkeroyd** [comment]
Created as draft PR as the most recent tech-talk post mentioned a failure to build `ezcaVarArrayTest.exe` that I will look into, but everything else built fine

**Comment by till-s** [comment]
Thanks Freddie - so do you recommend holding off merging the PR until you get a chance to look into the ezcaVarArrayTest issue?

**Comment by FreddieAkeroyd** [comment]
@till-s I've posted a reply on tech-talk so we can just see if it is something simple , as far as i can see it should work as is, i've not got a matlab installation locally but that part of the build does not require matlab and seems to work fine for me

**Comment by till-s** [comment]
OK - the PR is still marked as 'draft' (preventing it from being merged). Just let me know when it is ready for me to hit the button :-)

**Comment by AlessandroDUffizi** [comment]
"@FreddieAkeroyd
[Add epicsShareFunc to lcaMexGblInit](https://github.com/till-s/epics-labca/pull/8/commits/0f0ed3a3844d26e8fd9caea464cd3aa1d0d60e5b)

My experience on windows compilation is that this modification is fundamental. Otherwise the  lcaMexGbIInit won't be exported and the windows compilation fails.
Differently from Linux, Windows doesn't export library functions as default.
So I think is a good idea to merge

**Comment by till-s** [comment]
@FreddieAkeroyd - PR still markd as draft; could you please let me know when it is ready to be reviewed and merged?

**Comment by FreddieAkeroyd** [comment]
Hi, @till-s - I'm hoping it is nearly ready, I pushed some more updates and rebased last week as i'm helping another person who had trouble with it failing due to quoting at a different place. I think that quoting is now resolved, but he was also getting a compile error with  `lcaGetEnumStrings.c`  not finding 'EZCA_ENUM_STATES' which  I think that was due to it picking up another older `ezca.h`  from outside the labca distribution

**Comment by FreddieAkeroyd** [comment]
Hi @till-s have now had feedback that it looks good. He had initially installed ezca from the web not realising that labca bundled its own, but then epics build picked up this older ezca header. After removing the older ezca distribution all built fine.

**Pull request merged**
